package avutil

/*
#cgo LDFLAGS: -lavutil

#include "libavutil/avutil.h"

char* err2str(int errnum) {
	return av_err2str(errnum);
}
*/
import "C"

const (
	AVERROR_BSF_NOT_FOUND      = C.AVERROR_BSF_NOT_FOUND
	AVERROR_BUG                = C.AVERROR_BUG
	AVERROR_BUFFER_TOO_SMALL   = C.AVERROR_BUFFER_TOO_SMALL
	AVERROR_DECODER_NOT_FOUND  = C.AVERROR_DECODER_NOT_FOUND
	AVERROR_DEMUXER_NOT_FOUND  = C.AVERROR_DEMUXER_NOT_FOUND
	AVERROR_ENCODER_NOT_FOUND  = C.AVERROR_ENCODER_NOT_FOUND
	AVERROR_EOF                = C.AVERROR_EOF
	AVERROR_EXIT               = C.AVERROR_EXIT
	AVERROR_EXTERNAL           = C.AVERROR_EXTERNAL
	AVERROR_FILTER_NOT_FOUND   = C.AVERROR_FILTER_NOT_FOUND
	AVERROR_INVALIDDATA        = C.AVERROR_INVALIDDATA
	AVERROR_MUXER_NOT_FOUND    = C.AVERROR_MUXER_NOT_FOUND
	AVERROR_OPTION_NOT_FOUND   = C.AVERROR_OPTION_NOT_FOUND
	AVERROR_PATCHWELCOME       = C.AVERROR_PATCHWELCOME
	AVERROR_PROTOCOL_NOT_FOUND = C.AVERROR_PROTOCOL_NOT_FOUND

	AVERROR_STREAM_NOT_FOUND = C.AVERROR_STREAM_NOT_FOUND
	/**
	 * This is semantically identical to AVERROR_BUG
	 * it has been introduced in Libav after our AVERROR_BUG and with a modified value.
	 */
	AVERROR_BUG2           = C.AVERROR_BUG2
	AVERROR_UNKNOWN        = C.AVERROR_UNKNOWN
	AVERROR_EXPERIMENTAL   = C.AVERROR_EXPERIMENTAL
	AVERROR_INPUT_CHANGED  = C.AVERROR_INPUT_CHANGED
	AVERROR_OUTPUT_CHANGED = C.AVERROR_OUTPUT_CHANGED
	/* HTTP & RTSP errors */
	AVERROR_HTTP_BAD_REQUEST  = C.AVERROR_HTTP_BAD_REQUEST
	AVERROR_HTTP_UNAUTHORIZED = C.AVERROR_HTTP_UNAUTHORIZED
	AVERROR_HTTP_FORBIDDEN    = C.AVERROR_HTTP_FORBIDDEN
	AVERROR_HTTP_NOT_FOUND    = C.AVERROR_HTTP_NOT_FOUND
	AVERROR_HTTP_OTHER_4XX    = C.AVERROR_HTTP_OTHER_4XX
	AVERROR_HTTP_SERVER_ERROR = C.AVERROR_HTTP_SERVER_ERROR
)

func Err2str(code int) string {
	return C.GoString(C.err2str(1))
}
