package avcodec

/*
#cgo pkg-config: libavcodec

#include "libavcodec/codec_id.h"
*/
import "C"
import "github.com/Lensual/go-libav/avutil"

/**
 * Identify the syntax and semantics of the bitstream.
 * The principle is roughly:
 * Two decoders with the same ID can decode the same streams.
 * Two encoders with the same ID can encode compatible streams.
 * There may be slight deviations from the principle due to implementation
 * details.
 *
 * If you add a codec ID to this list add it so that
 * 1. no value of an existing codec ID changes (that would break ABI)
 * 2. it is as close as possible to similar codecs
 *
 * After adding new codec IDs do not forget to add an entry to the codec
 * descriptor list and bump libavcodec minor version.
 */

type CAVCodecID C.enum_AVCodecID

const (
	AV_CODEC_ID_NONE CAVCodecID = C.AV_CODEC_ID_NONE

	/* video codecs */
	AV_CODEC_ID_MPEG1VIDEO      CAVCodecID = C.AV_CODEC_ID_MPEG1VIDEO
	AV_CODEC_ID_MPEG2VIDEO      CAVCodecID = C.AV_CODEC_ID_MPEG2VIDEO ///< preferred ID for MPEG-1/2 video decoding
	AV_CODEC_ID_H261            CAVCodecID = C.AV_CODEC_ID_H261
	AV_CODEC_ID_H263            CAVCodecID = C.AV_CODEC_ID_H263
	AV_CODEC_ID_RV10            CAVCodecID = C.AV_CODEC_ID_RV10
	AV_CODEC_ID_RV20            CAVCodecID = C.AV_CODEC_ID_RV20
	AV_CODEC_ID_MJPEG           CAVCodecID = C.AV_CODEC_ID_MJPEG
	AV_CODEC_ID_MJPEGB          CAVCodecID = C.AV_CODEC_ID_MJPEGB
	AV_CODEC_ID_LJPEG           CAVCodecID = C.AV_CODEC_ID_LJPEG
	AV_CODEC_ID_SP5X            CAVCodecID = C.AV_CODEC_ID_SP5X
	AV_CODEC_ID_JPEGLS          CAVCodecID = C.AV_CODEC_ID_JPEGLS
	AV_CODEC_ID_MPEG4           CAVCodecID = C.AV_CODEC_ID_MPEG4
	AV_CODEC_ID_RAWVIDEO        CAVCodecID = C.AV_CODEC_ID_RAWVIDEO
	AV_CODEC_ID_MSMPEG4V1       CAVCodecID = C.AV_CODEC_ID_MSMPEG4V1
	AV_CODEC_ID_MSMPEG4V2       CAVCodecID = C.AV_CODEC_ID_MSMPEG4V2
	AV_CODEC_ID_MSMPEG4V3       CAVCodecID = C.AV_CODEC_ID_MSMPEG4V3
	AV_CODEC_ID_WMV1            CAVCodecID = C.AV_CODEC_ID_WMV1
	AV_CODEC_ID_WMV2            CAVCodecID = C.AV_CODEC_ID_WMV2
	AV_CODEC_ID_H263P           CAVCodecID = C.AV_CODEC_ID_H263P
	AV_CODEC_ID_H263I           CAVCodecID = C.AV_CODEC_ID_H263I
	AV_CODEC_ID_FLV1            CAVCodecID = C.AV_CODEC_ID_FLV1
	AV_CODEC_ID_SVQ1            CAVCodecID = C.AV_CODEC_ID_SVQ1
	AV_CODEC_ID_SVQ3            CAVCodecID = C.AV_CODEC_ID_SVQ3
	AV_CODEC_ID_DVVIDEO         CAVCodecID = C.AV_CODEC_ID_DVVIDEO
	AV_CODEC_ID_HUFFYUV         CAVCodecID = C.AV_CODEC_ID_HUFFYUV
	AV_CODEC_ID_CYUV            CAVCodecID = C.AV_CODEC_ID_CYUV
	AV_CODEC_ID_H264            CAVCodecID = C.AV_CODEC_ID_H264
	AV_CODEC_ID_INDEO3          CAVCodecID = C.AV_CODEC_ID_INDEO3
	AV_CODEC_ID_VP3             CAVCodecID = C.AV_CODEC_ID_VP3
	AV_CODEC_ID_THEORA          CAVCodecID = C.AV_CODEC_ID_THEORA
	AV_CODEC_ID_ASV1            CAVCodecID = C.AV_CODEC_ID_ASV1
	AV_CODEC_ID_ASV2            CAVCodecID = C.AV_CODEC_ID_ASV2
	AV_CODEC_ID_FFV1            CAVCodecID = C.AV_CODEC_ID_FFV1
	AV_CODEC_ID_4XM             CAVCodecID = C.AV_CODEC_ID_4XM
	AV_CODEC_ID_VCR1            CAVCodecID = C.AV_CODEC_ID_VCR1
	AV_CODEC_ID_CLJR            CAVCodecID = C.AV_CODEC_ID_CLJR
	AV_CODEC_ID_MDEC            CAVCodecID = C.AV_CODEC_ID_MDEC
	AV_CODEC_ID_ROQ             CAVCodecID = C.AV_CODEC_ID_ROQ
	AV_CODEC_ID_INTERPLAY_VIDEO CAVCodecID = C.AV_CODEC_ID_INTERPLAY_VIDEO
	AV_CODEC_ID_XAN_WC3         CAVCodecID = C.AV_CODEC_ID_XAN_WC3
	AV_CODEC_ID_XAN_WC4         CAVCodecID = C.AV_CODEC_ID_XAN_WC4
	AV_CODEC_ID_RPZA            CAVCodecID = C.AV_CODEC_ID_RPZA
	AV_CODEC_ID_CINEPAK         CAVCodecID = C.AV_CODEC_ID_CINEPAK
	AV_CODEC_ID_WS_VQA          CAVCodecID = C.AV_CODEC_ID_WS_VQA
	AV_CODEC_ID_MSRLE           CAVCodecID = C.AV_CODEC_ID_MSRLE
	AV_CODEC_ID_MSVIDEO1        CAVCodecID = C.AV_CODEC_ID_MSVIDEO1
	AV_CODEC_ID_IDCIN           CAVCodecID = C.AV_CODEC_ID_IDCIN
	AV_CODEC_ID_8BPS            CAVCodecID = C.AV_CODEC_ID_8BPS
	AV_CODEC_ID_SMC             CAVCodecID = C.AV_CODEC_ID_SMC
	AV_CODEC_ID_FLIC            CAVCodecID = C.AV_CODEC_ID_FLIC
	AV_CODEC_ID_TRUEMOTION1     CAVCodecID = C.AV_CODEC_ID_TRUEMOTION1
	AV_CODEC_ID_VMDVIDEO        CAVCodecID = C.AV_CODEC_ID_VMDVIDEO
	AV_CODEC_ID_MSZH            CAVCodecID = C.AV_CODEC_ID_MSZH
	AV_CODEC_ID_ZLIB            CAVCodecID = C.AV_CODEC_ID_ZLIB
	AV_CODEC_ID_QTRLE           CAVCodecID = C.AV_CODEC_ID_QTRLE
	AV_CODEC_ID_TSCC            CAVCodecID = C.AV_CODEC_ID_TSCC
	AV_CODEC_ID_ULTI            CAVCodecID = C.AV_CODEC_ID_ULTI
	AV_CODEC_ID_QDRAW           CAVCodecID = C.AV_CODEC_ID_QDRAW
	AV_CODEC_ID_VIXL            CAVCodecID = C.AV_CODEC_ID_VIXL
	AV_CODEC_ID_QPEG            CAVCodecID = C.AV_CODEC_ID_QPEG
	AV_CODEC_ID_PNG             CAVCodecID = C.AV_CODEC_ID_PNG
	AV_CODEC_ID_PPM             CAVCodecID = C.AV_CODEC_ID_PPM
	AV_CODEC_ID_PBM             CAVCodecID = C.AV_CODEC_ID_PBM
	AV_CODEC_ID_PGM             CAVCodecID = C.AV_CODEC_ID_PGM
	AV_CODEC_ID_PGMYUV          CAVCodecID = C.AV_CODEC_ID_PGMYUV
	AV_CODEC_ID_PAM             CAVCodecID = C.AV_CODEC_ID_PAM
	AV_CODEC_ID_FFVHUFF         CAVCodecID = C.AV_CODEC_ID_FFVHUFF
	AV_CODEC_ID_RV30            CAVCodecID = C.AV_CODEC_ID_RV30
	AV_CODEC_ID_RV40            CAVCodecID = C.AV_CODEC_ID_RV40
	AV_CODEC_ID_VC1             CAVCodecID = C.AV_CODEC_ID_VC1
	AV_CODEC_ID_WMV3            CAVCodecID = C.AV_CODEC_ID_WMV3
	AV_CODEC_ID_LOCO            CAVCodecID = C.AV_CODEC_ID_LOCO
	AV_CODEC_ID_WNV1            CAVCodecID = C.AV_CODEC_ID_WNV1
	AV_CODEC_ID_AASC            CAVCodecID = C.AV_CODEC_ID_AASC
	AV_CODEC_ID_INDEO2          CAVCodecID = C.AV_CODEC_ID_INDEO2
	AV_CODEC_ID_FRAPS           CAVCodecID = C.AV_CODEC_ID_FRAPS
	AV_CODEC_ID_TRUEMOTION2     CAVCodecID = C.AV_CODEC_ID_TRUEMOTION2
	AV_CODEC_ID_BMP             CAVCodecID = C.AV_CODEC_ID_BMP
	AV_CODEC_ID_CSCD            CAVCodecID = C.AV_CODEC_ID_CSCD
	AV_CODEC_ID_MMVIDEO         CAVCodecID = C.AV_CODEC_ID_MMVIDEO
	AV_CODEC_ID_ZMBV            CAVCodecID = C.AV_CODEC_ID_ZMBV
	AV_CODEC_ID_AVS             CAVCodecID = C.AV_CODEC_ID_AVS
	AV_CODEC_ID_SMACKVIDEO      CAVCodecID = C.AV_CODEC_ID_SMACKVIDEO
	AV_CODEC_ID_NUV             CAVCodecID = C.AV_CODEC_ID_NUV
	AV_CODEC_ID_KMVC            CAVCodecID = C.AV_CODEC_ID_KMVC
	AV_CODEC_ID_FLASHSV         CAVCodecID = C.AV_CODEC_ID_FLASHSV
	AV_CODEC_ID_CAVS            CAVCodecID = C.AV_CODEC_ID_CAVS
	AV_CODEC_ID_JPEG2000        CAVCodecID = C.AV_CODEC_ID_JPEG2000
	AV_CODEC_ID_VMNC            CAVCodecID = C.AV_CODEC_ID_VMNC
	AV_CODEC_ID_VP5             CAVCodecID = C.AV_CODEC_ID_VP5
	AV_CODEC_ID_VP6             CAVCodecID = C.AV_CODEC_ID_VP6
	AV_CODEC_ID_VP6F            CAVCodecID = C.AV_CODEC_ID_VP6F
	AV_CODEC_ID_TARGA           CAVCodecID = C.AV_CODEC_ID_TARGA
	AV_CODEC_ID_DSICINVIDEO     CAVCodecID = C.AV_CODEC_ID_DSICINVIDEO
	AV_CODEC_ID_TIERTEXSEQVIDEO CAVCodecID = C.AV_CODEC_ID_TIERTEXSEQVIDEO
	AV_CODEC_ID_TIFF            CAVCodecID = C.AV_CODEC_ID_TIFF
	AV_CODEC_ID_GIF             CAVCodecID = C.AV_CODEC_ID_GIF
	AV_CODEC_ID_DXA             CAVCodecID = C.AV_CODEC_ID_DXA
	AV_CODEC_ID_DNXHD           CAVCodecID = C.AV_CODEC_ID_DNXHD
	AV_CODEC_ID_THP             CAVCodecID = C.AV_CODEC_ID_THP
	AV_CODEC_ID_SGI             CAVCodecID = C.AV_CODEC_ID_SGI
	AV_CODEC_ID_C93             CAVCodecID = C.AV_CODEC_ID_C93
	AV_CODEC_ID_BETHSOFTVID     CAVCodecID = C.AV_CODEC_ID_BETHSOFTVID
	AV_CODEC_ID_PTX             CAVCodecID = C.AV_CODEC_ID_PTX
	AV_CODEC_ID_TXD             CAVCodecID = C.AV_CODEC_ID_TXD
	AV_CODEC_ID_VP6A            CAVCodecID = C.AV_CODEC_ID_VP6A
	AV_CODEC_ID_AMV             CAVCodecID = C.AV_CODEC_ID_AMV
	AV_CODEC_ID_VB              CAVCodecID = C.AV_CODEC_ID_VB
	AV_CODEC_ID_PCX             CAVCodecID = C.AV_CODEC_ID_PCX
	AV_CODEC_ID_SUNRAST         CAVCodecID = C.AV_CODEC_ID_SUNRAST
	AV_CODEC_ID_INDEO4          CAVCodecID = C.AV_CODEC_ID_INDEO4
	AV_CODEC_ID_INDEO5          CAVCodecID = C.AV_CODEC_ID_INDEO5
	AV_CODEC_ID_MIMIC           CAVCodecID = C.AV_CODEC_ID_MIMIC
	AV_CODEC_ID_RL2             CAVCodecID = C.AV_CODEC_ID_RL2
	AV_CODEC_ID_ESCAPE124       CAVCodecID = C.AV_CODEC_ID_ESCAPE124
	AV_CODEC_ID_DIRAC           CAVCodecID = C.AV_CODEC_ID_DIRAC
	AV_CODEC_ID_BFI             CAVCodecID = C.AV_CODEC_ID_BFI
	AV_CODEC_ID_CMV             CAVCodecID = C.AV_CODEC_ID_CMV
	AV_CODEC_ID_MOTIONPIXELS    CAVCodecID = C.AV_CODEC_ID_MOTIONPIXELS
	AV_CODEC_ID_TGV             CAVCodecID = C.AV_CODEC_ID_TGV
	AV_CODEC_ID_TGQ             CAVCodecID = C.AV_CODEC_ID_TGQ
	AV_CODEC_ID_TQI             CAVCodecID = C.AV_CODEC_ID_TQI
	AV_CODEC_ID_AURA            CAVCodecID = C.AV_CODEC_ID_AURA
	AV_CODEC_ID_AURA2           CAVCodecID = C.AV_CODEC_ID_AURA2
	AV_CODEC_ID_V210X           CAVCodecID = C.AV_CODEC_ID_V210X
	AV_CODEC_ID_TMV             CAVCodecID = C.AV_CODEC_ID_TMV
	AV_CODEC_ID_V210            CAVCodecID = C.AV_CODEC_ID_V210
	AV_CODEC_ID_DPX             CAVCodecID = C.AV_CODEC_ID_DPX
	AV_CODEC_ID_MAD             CAVCodecID = C.AV_CODEC_ID_MAD
	AV_CODEC_ID_FRWU            CAVCodecID = C.AV_CODEC_ID_FRWU
	AV_CODEC_ID_FLASHSV2        CAVCodecID = C.AV_CODEC_ID_FLASHSV2
	AV_CODEC_ID_CDGRAPHICS      CAVCodecID = C.AV_CODEC_ID_CDGRAPHICS
	AV_CODEC_ID_R210            CAVCodecID = C.AV_CODEC_ID_R210
	AV_CODEC_ID_ANM             CAVCodecID = C.AV_CODEC_ID_ANM
	AV_CODEC_ID_BINKVIDEO       CAVCodecID = C.AV_CODEC_ID_BINKVIDEO
	AV_CODEC_ID_IFF_ILBM        CAVCodecID = C.AV_CODEC_ID_IFF_ILBM
	AV_CODEC_ID_IFF_BYTERUN1    CAVCodecID = C.AV_CODEC_ID_IFF_ILBM
	AV_CODEC_ID_KGV1            CAVCodecID = C.AV_CODEC_ID_KGV1
	AV_CODEC_ID_YOP             CAVCodecID = C.AV_CODEC_ID_YOP
	AV_CODEC_ID_VP8             CAVCodecID = C.AV_CODEC_ID_VP8
	AV_CODEC_ID_PICTOR          CAVCodecID = C.AV_CODEC_ID_PICTOR
	AV_CODEC_ID_ANSI            CAVCodecID = C.AV_CODEC_ID_ANSI
	AV_CODEC_ID_A64_MULTI       CAVCodecID = C.AV_CODEC_ID_A64_MULTI
	AV_CODEC_ID_A64_MULTI5      CAVCodecID = C.AV_CODEC_ID_A64_MULTI5
	AV_CODEC_ID_R10K            CAVCodecID = C.AV_CODEC_ID_R10K
	AV_CODEC_ID_MXPEG           CAVCodecID = C.AV_CODEC_ID_MXPEG
	AV_CODEC_ID_LAGARITH        CAVCodecID = C.AV_CODEC_ID_LAGARITH
	AV_CODEC_ID_PRORES          CAVCodecID = C.AV_CODEC_ID_PRORES
	AV_CODEC_ID_JV              CAVCodecID = C.AV_CODEC_ID_JV
	AV_CODEC_ID_DFA             CAVCodecID = C.AV_CODEC_ID_DFA
	AV_CODEC_ID_WMV3IMAGE       CAVCodecID = C.AV_CODEC_ID_WMV3IMAGE
	AV_CODEC_ID_VC1IMAGE        CAVCodecID = C.AV_CODEC_ID_VC1IMAGE
	AV_CODEC_ID_UTVIDEO         CAVCodecID = C.AV_CODEC_ID_UTVIDEO
	AV_CODEC_ID_BMV_VIDEO       CAVCodecID = C.AV_CODEC_ID_BMV_VIDEO
	AV_CODEC_ID_VBLE            CAVCodecID = C.AV_CODEC_ID_VBLE
	AV_CODEC_ID_DXTORY          CAVCodecID = C.AV_CODEC_ID_DXTORY
	AV_CODEC_ID_V410            CAVCodecID = C.AV_CODEC_ID_V410
	AV_CODEC_ID_XWD             CAVCodecID = C.AV_CODEC_ID_XWD
	AV_CODEC_ID_CDXL            CAVCodecID = C.AV_CODEC_ID_CDXL
	AV_CODEC_ID_XBM             CAVCodecID = C.AV_CODEC_ID_XBM
	AV_CODEC_ID_ZEROCODEC       CAVCodecID = C.AV_CODEC_ID_ZEROCODEC
	AV_CODEC_ID_MSS1            CAVCodecID = C.AV_CODEC_ID_MSS1
	AV_CODEC_ID_MSA1            CAVCodecID = C.AV_CODEC_ID_MSA1
	AV_CODEC_ID_TSCC2           CAVCodecID = C.AV_CODEC_ID_TSCC2
	AV_CODEC_ID_MTS2            CAVCodecID = C.AV_CODEC_ID_MTS2
	AV_CODEC_ID_CLLC            CAVCodecID = C.AV_CODEC_ID_CLLC
	AV_CODEC_ID_MSS2            CAVCodecID = C.AV_CODEC_ID_MSS2
	AV_CODEC_ID_VP9             CAVCodecID = C.AV_CODEC_ID_VP9
	AV_CODEC_ID_AIC             CAVCodecID = C.AV_CODEC_ID_AIC
	AV_CODEC_ID_ESCAPE130       CAVCodecID = C.AV_CODEC_ID_ESCAPE130
	AV_CODEC_ID_G2M             CAVCodecID = C.AV_CODEC_ID_G2M
	AV_CODEC_ID_WEBP            CAVCodecID = C.AV_CODEC_ID_WEBP
	AV_CODEC_ID_HNM4_VIDEO      CAVCodecID = C.AV_CODEC_ID_HNM4_VIDEO
	AV_CODEC_ID_HEVC            CAVCodecID = C.AV_CODEC_ID_HEVC
	AV_CODEC_ID_H265            CAVCodecID = C.AV_CODEC_ID_H265
	AV_CODEC_ID_FIC             CAVCodecID = C.AV_CODEC_ID_FIC
	AV_CODEC_ID_ALIAS_PIX       CAVCodecID = C.AV_CODEC_ID_ALIAS_PIX
	AV_CODEC_ID_BRENDER_PIX     CAVCodecID = C.AV_CODEC_ID_BRENDER_PIX
	AV_CODEC_ID_PAF_VIDEO       CAVCodecID = C.AV_CODEC_ID_PAF_VIDEO
	AV_CODEC_ID_EXR             CAVCodecID = C.AV_CODEC_ID_EXR
	AV_CODEC_ID_VP7             CAVCodecID = C.AV_CODEC_ID_VP7
	AV_CODEC_ID_SANM            CAVCodecID = C.AV_CODEC_ID_SANM
	AV_CODEC_ID_SGIRLE          CAVCodecID = C.AV_CODEC_ID_SGIRLE
	AV_CODEC_ID_MVC1            CAVCodecID = C.AV_CODEC_ID_MVC1
	AV_CODEC_ID_MVC2            CAVCodecID = C.AV_CODEC_ID_MVC2
	AV_CODEC_ID_HQX             CAVCodecID = C.AV_CODEC_ID_HQX
	AV_CODEC_ID_TDSC            CAVCodecID = C.AV_CODEC_ID_TDSC
	AV_CODEC_ID_HQ_HQA          CAVCodecID = C.AV_CODEC_ID_HQ_HQA
	AV_CODEC_ID_HAP             CAVCodecID = C.AV_CODEC_ID_HAP
	AV_CODEC_ID_DDS             CAVCodecID = C.AV_CODEC_ID_DDS
	AV_CODEC_ID_DXV             CAVCodecID = C.AV_CODEC_ID_DXV
	AV_CODEC_ID_SCREENPRESSO    CAVCodecID = C.AV_CODEC_ID_SCREENPRESSO
	AV_CODEC_ID_RSCC            CAVCodecID = C.AV_CODEC_ID_RSCC
	AV_CODEC_ID_AVS2            CAVCodecID = C.AV_CODEC_ID_AVS2
	AV_CODEC_ID_PGX             CAVCodecID = C.AV_CODEC_ID_PGX
	AV_CODEC_ID_AVS3            CAVCodecID = C.AV_CODEC_ID_AVS3
	AV_CODEC_ID_MSP2            CAVCodecID = C.AV_CODEC_ID_MSP2
	AV_CODEC_ID_VVC             CAVCodecID = C.AV_CODEC_ID_VVC
	AV_CODEC_ID_H266            CAVCodecID = C.AV_CODEC_ID_H266
	AV_CODEC_ID_Y41P            CAVCodecID = C.AV_CODEC_ID_Y41P
	AV_CODEC_ID_AVRP            CAVCodecID = C.AV_CODEC_ID_AVRP
	AV_CODEC_ID_012V            CAVCodecID = C.AV_CODEC_ID_012V
	AV_CODEC_ID_AVUI            CAVCodecID = C.AV_CODEC_ID_AVUI

	AV_CODEC_ID_AYUV CAVCodecID = C.AV_CODEC_ID_AYUV

	AV_CODEC_ID_TARGA_Y216    CAVCodecID = C.AV_CODEC_ID_TARGA_Y216
	AV_CODEC_ID_V308          CAVCodecID = C.AV_CODEC_ID_V308
	AV_CODEC_ID_V408          CAVCodecID = C.AV_CODEC_ID_V408
	AV_CODEC_ID_YUV4          CAVCodecID = C.AV_CODEC_ID_YUV4
	AV_CODEC_ID_AVRN          CAVCodecID = C.AV_CODEC_ID_AVRN
	AV_CODEC_ID_CPIA          CAVCodecID = C.AV_CODEC_ID_CPIA
	AV_CODEC_ID_XFACE         CAVCodecID = C.AV_CODEC_ID_XFACE
	AV_CODEC_ID_SNOW          CAVCodecID = C.AV_CODEC_ID_SNOW
	AV_CODEC_ID_SMVJPEG       CAVCodecID = C.AV_CODEC_ID_SMVJPEG
	AV_CODEC_ID_APNG          CAVCodecID = C.AV_CODEC_ID_APNG
	AV_CODEC_ID_DAALA         CAVCodecID = C.AV_CODEC_ID_DAALA
	AV_CODEC_ID_CFHD          CAVCodecID = C.AV_CODEC_ID_CFHD
	AV_CODEC_ID_TRUEMOTION2RT CAVCodecID = C.AV_CODEC_ID_TRUEMOTION2RT
	AV_CODEC_ID_M101          CAVCodecID = C.AV_CODEC_ID_M101
	AV_CODEC_ID_MAGICYUV      CAVCodecID = C.AV_CODEC_ID_MAGICYUV
	AV_CODEC_ID_SHEERVIDEO    CAVCodecID = C.AV_CODEC_ID_SHEERVIDEO
	AV_CODEC_ID_YLC           CAVCodecID = C.AV_CODEC_ID_YLC
	AV_CODEC_ID_PSD           CAVCodecID = C.AV_CODEC_ID_PSD
	AV_CODEC_ID_PIXLET        CAVCodecID = C.AV_CODEC_ID_PIXLET
	AV_CODEC_ID_SPEEDHQ       CAVCodecID = C.AV_CODEC_ID_SPEEDHQ
	AV_CODEC_ID_FMVC          CAVCodecID = C.AV_CODEC_ID_FMVC
	AV_CODEC_ID_SCPR          CAVCodecID = C.AV_CODEC_ID_SCPR
	AV_CODEC_ID_CLEARVIDEO    CAVCodecID = C.AV_CODEC_ID_CLEARVIDEO
	AV_CODEC_ID_XPM           CAVCodecID = C.AV_CODEC_ID_XPM
	AV_CODEC_ID_AV1           CAVCodecID = C.AV_CODEC_ID_AV1
	AV_CODEC_ID_BITPACKED     CAVCodecID = C.AV_CODEC_ID_BITPACKED
	AV_CODEC_ID_MSCC          CAVCodecID = C.AV_CODEC_ID_MSCC
	AV_CODEC_ID_SRGC          CAVCodecID = C.AV_CODEC_ID_SRGC
	AV_CODEC_ID_SVG           CAVCodecID = C.AV_CODEC_ID_SVG
	AV_CODEC_ID_GDV           CAVCodecID = C.AV_CODEC_ID_GDV
	AV_CODEC_ID_FITS          CAVCodecID = C.AV_CODEC_ID_FITS
	AV_CODEC_ID_IMM4          CAVCodecID = C.AV_CODEC_ID_IMM4
	AV_CODEC_ID_PROSUMER      CAVCodecID = C.AV_CODEC_ID_PROSUMER
	AV_CODEC_ID_MWSC          CAVCodecID = C.AV_CODEC_ID_MWSC
	AV_CODEC_ID_WCMV          CAVCodecID = C.AV_CODEC_ID_WCMV
	AV_CODEC_ID_RASC          CAVCodecID = C.AV_CODEC_ID_RASC
	AV_CODEC_ID_HYMT          CAVCodecID = C.AV_CODEC_ID_HYMT
	AV_CODEC_ID_ARBC          CAVCodecID = C.AV_CODEC_ID_ARBC
	AV_CODEC_ID_AGM           CAVCodecID = C.AV_CODEC_ID_AGM
	AV_CODEC_ID_LSCR          CAVCodecID = C.AV_CODEC_ID_LSCR
	AV_CODEC_ID_VP4           CAVCodecID = C.AV_CODEC_ID_VP4
	AV_CODEC_ID_IMM5          CAVCodecID = C.AV_CODEC_ID_IMM5
	AV_CODEC_ID_MVDV          CAVCodecID = C.AV_CODEC_ID_MVDV
	AV_CODEC_ID_MVHA          CAVCodecID = C.AV_CODEC_ID_MVHA
	AV_CODEC_ID_CDTOONS       CAVCodecID = C.AV_CODEC_ID_CDTOONS
	AV_CODEC_ID_MV30          CAVCodecID = C.AV_CODEC_ID_MV30
	AV_CODEC_ID_NOTCHLC       CAVCodecID = C.AV_CODEC_ID_NOTCHLC
	AV_CODEC_ID_PFM           CAVCodecID = C.AV_CODEC_ID_PFM
	AV_CODEC_ID_MOBICLIP      CAVCodecID = C.AV_CODEC_ID_MOBICLIP
	AV_CODEC_ID_PHOTOCD       CAVCodecID = C.AV_CODEC_ID_PHOTOCD
	AV_CODEC_ID_IPU           CAVCodecID = C.AV_CODEC_ID_IPU
	AV_CODEC_ID_ARGO          CAVCodecID = C.AV_CODEC_ID_ARGO
	AV_CODEC_ID_CRI           CAVCodecID = C.AV_CODEC_ID_CRI
	AV_CODEC_ID_SIMBIOSIS_IMX CAVCodecID = C.AV_CODEC_ID_SIMBIOSIS_IMX
	AV_CODEC_ID_SGA_VIDEO     CAVCodecID = C.AV_CODEC_ID_SGA_VIDEO
	AV_CODEC_ID_GEM           CAVCodecID = C.AV_CODEC_ID_GEM
	AV_CODEC_ID_VBN           CAVCodecID = C.AV_CODEC_ID_VBN
	AV_CODEC_ID_JPEGXL        CAVCodecID = C.AV_CODEC_ID_JPEGXL
	AV_CODEC_ID_QOI           CAVCodecID = C.AV_CODEC_ID_QOI
	AV_CODEC_ID_PHM           CAVCodecID = C.AV_CODEC_ID_PHM
	AV_CODEC_ID_RADIANCE_HDR  CAVCodecID = C.AV_CODEC_ID_RADIANCE_HDR
	AV_CODEC_ID_WBMP          CAVCodecID = C.AV_CODEC_ID_WBMP
	AV_CODEC_ID_MEDIA100      CAVCodecID = C.AV_CODEC_ID_MEDIA100
	AV_CODEC_ID_VQC           CAVCodecID = C.AV_CODEC_ID_VQC
	AV_CODEC_ID_PDV           CAVCodecID = C.AV_CODEC_ID_PDV
	AV_CODEC_ID_EVC           CAVCodecID = C.AV_CODEC_ID_EVC
	AV_CODEC_ID_RTV1          CAVCodecID = C.AV_CODEC_ID_RTV1
	AV_CODEC_ID_VMIX          CAVCodecID = C.AV_CODEC_ID_VMIX

	/* various PCM "codecs" */
	AV_CODEC_ID_FIRST_AUDIO      CAVCodecID = C.AV_CODEC_ID_FIRST_AUDIO ///< A dummy id pointing at the start of audio codecs
	AV_CODEC_ID_PCM_S16LE        CAVCodecID = C.AV_CODEC_ID_PCM_S16LE
	AV_CODEC_ID_PCM_S16BE        CAVCodecID = C.AV_CODEC_ID_PCM_S16BE
	AV_CODEC_ID_PCM_U16LE        CAVCodecID = C.AV_CODEC_ID_PCM_U16LE
	AV_CODEC_ID_PCM_U16BE        CAVCodecID = C.AV_CODEC_ID_PCM_U16BE
	AV_CODEC_ID_PCM_S8           CAVCodecID = C.AV_CODEC_ID_PCM_S8
	AV_CODEC_ID_PCM_U8           CAVCodecID = C.AV_CODEC_ID_PCM_U8
	AV_CODEC_ID_PCM_MULAW        CAVCodecID = C.AV_CODEC_ID_PCM_MULAW
	AV_CODEC_ID_PCM_ALAW         CAVCodecID = C.AV_CODEC_ID_PCM_ALAW
	AV_CODEC_ID_PCM_S32LE        CAVCodecID = C.AV_CODEC_ID_PCM_S32LE
	AV_CODEC_ID_PCM_S32BE        CAVCodecID = C.AV_CODEC_ID_PCM_S32BE
	AV_CODEC_ID_PCM_U32LE        CAVCodecID = C.AV_CODEC_ID_PCM_U32LE
	AV_CODEC_ID_PCM_U32BE        CAVCodecID = C.AV_CODEC_ID_PCM_U32BE
	AV_CODEC_ID_PCM_S24LE        CAVCodecID = C.AV_CODEC_ID_PCM_S24LE
	AV_CODEC_ID_PCM_S24BE        CAVCodecID = C.AV_CODEC_ID_PCM_S24BE
	AV_CODEC_ID_PCM_U24LE        CAVCodecID = C.AV_CODEC_ID_PCM_U24LE
	AV_CODEC_ID_PCM_U24BE        CAVCodecID = C.AV_CODEC_ID_PCM_U24BE
	AV_CODEC_ID_PCM_S24DAUD      CAVCodecID = C.AV_CODEC_ID_PCM_S24DAUD
	AV_CODEC_ID_PCM_ZORK         CAVCodecID = C.AV_CODEC_ID_PCM_ZORK
	AV_CODEC_ID_PCM_S16LE_PLANAR CAVCodecID = C.AV_CODEC_ID_PCM_S16LE_PLANAR
	AV_CODEC_ID_PCM_DVD          CAVCodecID = C.AV_CODEC_ID_PCM_DVD
	AV_CODEC_ID_PCM_F32BE        CAVCodecID = C.AV_CODEC_ID_PCM_F32BE
	AV_CODEC_ID_PCM_F32LE        CAVCodecID = C.AV_CODEC_ID_PCM_F32LE
	AV_CODEC_ID_PCM_F64BE        CAVCodecID = C.AV_CODEC_ID_PCM_F64BE
	AV_CODEC_ID_PCM_F64LE        CAVCodecID = C.AV_CODEC_ID_PCM_F64LE
	AV_CODEC_ID_PCM_BLURAY       CAVCodecID = C.AV_CODEC_ID_PCM_BLURAY
	AV_CODEC_ID_PCM_LXF          CAVCodecID = C.AV_CODEC_ID_PCM_LXF
	AV_CODEC_ID_S302M            CAVCodecID = C.AV_CODEC_ID_S302M
	AV_CODEC_ID_PCM_S8_PLANAR    CAVCodecID = C.AV_CODEC_ID_PCM_S8_PLANAR
	AV_CODEC_ID_PCM_S24LE_PLANAR CAVCodecID = C.AV_CODEC_ID_PCM_S24LE_PLANAR
	AV_CODEC_ID_PCM_S32LE_PLANAR CAVCodecID = C.AV_CODEC_ID_PCM_S32LE_PLANAR
	AV_CODEC_ID_PCM_S16BE_PLANAR CAVCodecID = C.AV_CODEC_ID_PCM_S16BE_PLANAR
	AV_CODEC_ID_PCM_S64LE        CAVCodecID = C.AV_CODEC_ID_PCM_S64LE
	AV_CODEC_ID_PCM_S64BE        CAVCodecID = C.AV_CODEC_ID_PCM_S64BE
	AV_CODEC_ID_PCM_F16LE        CAVCodecID = C.AV_CODEC_ID_PCM_F16LE
	AV_CODEC_ID_PCM_F24LE        CAVCodecID = C.AV_CODEC_ID_PCM_F24LE
	AV_CODEC_ID_PCM_VIDC         CAVCodecID = C.AV_CODEC_ID_PCM_VIDC
	AV_CODEC_ID_PCM_SGA          CAVCodecID = C.AV_CODEC_ID_PCM_SGA

	/* various ADPCM codecs */
	AV_CODEC_ID_ADPCM_IMA_QT      CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_QT
	AV_CODEC_ID_ADPCM_IMA_WAV     CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_WAV
	AV_CODEC_ID_ADPCM_IMA_DK3     CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_DK3
	AV_CODEC_ID_ADPCM_IMA_DK4     CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_DK4
	AV_CODEC_ID_ADPCM_IMA_WS      CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_WS
	AV_CODEC_ID_ADPCM_IMA_SMJPEG  CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_SMJPEG
	AV_CODEC_ID_ADPCM_MS          CAVCodecID = C.AV_CODEC_ID_ADPCM_MS
	AV_CODEC_ID_ADPCM_4XM         CAVCodecID = C.AV_CODEC_ID_ADPCM_4XM
	AV_CODEC_ID_ADPCM_XA          CAVCodecID = C.AV_CODEC_ID_ADPCM_XA
	AV_CODEC_ID_ADPCM_ADX         CAVCodecID = C.AV_CODEC_ID_ADPCM_ADX
	AV_CODEC_ID_ADPCM_EA          CAVCodecID = C.AV_CODEC_ID_ADPCM_EA
	AV_CODEC_ID_ADPCM_G726        CAVCodecID = C.AV_CODEC_ID_ADPCM_G726
	AV_CODEC_ID_ADPCM_CT          CAVCodecID = C.AV_CODEC_ID_ADPCM_CT
	AV_CODEC_ID_ADPCM_SWF         CAVCodecID = C.AV_CODEC_ID_ADPCM_SWF
	AV_CODEC_ID_ADPCM_YAMAHA      CAVCodecID = C.AV_CODEC_ID_ADPCM_YAMAHA
	AV_CODEC_ID_ADPCM_SBPRO_4     CAVCodecID = C.AV_CODEC_ID_ADPCM_SBPRO_4
	AV_CODEC_ID_ADPCM_SBPRO_3     CAVCodecID = C.AV_CODEC_ID_ADPCM_SBPRO_3
	AV_CODEC_ID_ADPCM_SBPRO_2     CAVCodecID = C.AV_CODEC_ID_ADPCM_SBPRO_2
	AV_CODEC_ID_ADPCM_THP         CAVCodecID = C.AV_CODEC_ID_ADPCM_THP
	AV_CODEC_ID_ADPCM_IMA_AMV     CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_AMV
	AV_CODEC_ID_ADPCM_EA_R1       CAVCodecID = C.AV_CODEC_ID_ADPCM_EA_R1
	AV_CODEC_ID_ADPCM_EA_R3       CAVCodecID = C.AV_CODEC_ID_ADPCM_EA_R3
	AV_CODEC_ID_ADPCM_EA_R2       CAVCodecID = C.AV_CODEC_ID_ADPCM_EA_R2
	AV_CODEC_ID_ADPCM_IMA_EA_SEAD CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_EA_SEAD
	AV_CODEC_ID_ADPCM_IMA_EA_EACS CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_EA_EACS
	AV_CODEC_ID_ADPCM_EA_XAS      CAVCodecID = C.AV_CODEC_ID_ADPCM_EA_XAS
	AV_CODEC_ID_ADPCM_EA_MAXIS_XA CAVCodecID = C.AV_CODEC_ID_ADPCM_EA_MAXIS_XA
	AV_CODEC_ID_ADPCM_IMA_ISS     CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_ISS
	AV_CODEC_ID_ADPCM_G722        CAVCodecID = C.AV_CODEC_ID_ADPCM_G722
	AV_CODEC_ID_ADPCM_IMA_APC     CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_APC
	AV_CODEC_ID_ADPCM_VIMA        CAVCodecID = C.AV_CODEC_ID_ADPCM_VIMA
	AV_CODEC_ID_ADPCM_AFC         CAVCodecID = C.AV_CODEC_ID_ADPCM_AFC
	AV_CODEC_ID_ADPCM_IMA_OKI     CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_OKI
	AV_CODEC_ID_ADPCM_DTK         CAVCodecID = C.AV_CODEC_ID_ADPCM_DTK
	AV_CODEC_ID_ADPCM_IMA_RAD     CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_RAD
	AV_CODEC_ID_ADPCM_G726LE      CAVCodecID = C.AV_CODEC_ID_ADPCM_G726LE
	AV_CODEC_ID_ADPCM_THP_LE      CAVCodecID = C.AV_CODEC_ID_ADPCM_THP_LE
	AV_CODEC_ID_ADPCM_PSX         CAVCodecID = C.AV_CODEC_ID_ADPCM_PSX
	AV_CODEC_ID_ADPCM_AICA        CAVCodecID = C.AV_CODEC_ID_ADPCM_AICA
	AV_CODEC_ID_ADPCM_IMA_DAT4    CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_DAT4
	AV_CODEC_ID_ADPCM_MTAF        CAVCodecID = C.AV_CODEC_ID_ADPCM_MTAF
	AV_CODEC_ID_ADPCM_AGM         CAVCodecID = C.AV_CODEC_ID_ADPCM_AGM
	AV_CODEC_ID_ADPCM_ARGO        CAVCodecID = C.AV_CODEC_ID_ADPCM_ARGO
	AV_CODEC_ID_ADPCM_IMA_SSI     CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_SSI
	AV_CODEC_ID_ADPCM_ZORK        CAVCodecID = C.AV_CODEC_ID_ADPCM_ZORK
	AV_CODEC_ID_ADPCM_IMA_APM     CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_APM
	AV_CODEC_ID_ADPCM_IMA_ALP     CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_ALP
	AV_CODEC_ID_ADPCM_IMA_MTF     CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_MTF
	AV_CODEC_ID_ADPCM_IMA_CUNNING CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_CUNNING
	AV_CODEC_ID_ADPCM_IMA_MOFLEX  CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_MOFLEX
	AV_CODEC_ID_ADPCM_IMA_ACORN   CAVCodecID = C.AV_CODEC_ID_ADPCM_IMA_ACORN
	AV_CODEC_ID_ADPCM_XMD         CAVCodecID = C.AV_CODEC_ID_ADPCM_XMD

	/* AMR */
	AV_CODEC_ID_AMR_NB CAVCodecID = C.AV_CODEC_ID_AMR_NB
	AV_CODEC_ID_AMR_WB CAVCodecID = C.AV_CODEC_ID_AMR_WB

	/* RealAudio codecs*/
	AV_CODEC_ID_RA_144 CAVCodecID = C.AV_CODEC_ID_RA_144
	AV_CODEC_ID_RA_288 CAVCodecID = C.AV_CODEC_ID_RA_288

	/* various DPCM codecs */
	AV_CODEC_ID_ROQ_DPCM       CAVCodecID = C.AV_CODEC_ID_ROQ_DPCM
	AV_CODEC_ID_INTERPLAY_DPCM CAVCodecID = C.AV_CODEC_ID_INTERPLAY_DPCM
	AV_CODEC_ID_XAN_DPCM       CAVCodecID = C.AV_CODEC_ID_XAN_DPCM
	AV_CODEC_ID_SOL_DPCM       CAVCodecID = C.AV_CODEC_ID_SOL_DPCM
	AV_CODEC_ID_SDX2_DPCM      CAVCodecID = C.AV_CODEC_ID_SDX2_DPCM
	AV_CODEC_ID_GREMLIN_DPCM   CAVCodecID = C.AV_CODEC_ID_GREMLIN_DPCM
	AV_CODEC_ID_DERF_DPCM      CAVCodecID = C.AV_CODEC_ID_DERF_DPCM
	AV_CODEC_ID_WADY_DPCM      CAVCodecID = C.AV_CODEC_ID_WADY_DPCM
	AV_CODEC_ID_CBD2_DPCM      CAVCodecID = C.AV_CODEC_ID_CBD2_DPCM

	/* audio codecs */
	AV_CODEC_ID_MP2             CAVCodecID = C.AV_CODEC_ID_MP2
	AV_CODEC_ID_MP3             CAVCodecID = C.AV_CODEC_ID_MP3 ///< preferred ID for decoding MPEG audio layer 1 2 or 3
	AV_CODEC_ID_AAC             CAVCodecID = C.AV_CODEC_ID_AAC
	AV_CODEC_ID_AC3             CAVCodecID = C.AV_CODEC_ID_AC3
	AV_CODEC_ID_DTS             CAVCodecID = C.AV_CODEC_ID_DTS
	AV_CODEC_ID_VORBIS          CAVCodecID = C.AV_CODEC_ID_VORBIS
	AV_CODEC_ID_DVAUDIO         CAVCodecID = C.AV_CODEC_ID_DVAUDIO
	AV_CODEC_ID_WMAV1           CAVCodecID = C.AV_CODEC_ID_WMAV1
	AV_CODEC_ID_WMAV2           CAVCodecID = C.AV_CODEC_ID_WMAV2
	AV_CODEC_ID_MACE3           CAVCodecID = C.AV_CODEC_ID_MACE3
	AV_CODEC_ID_MACE6           CAVCodecID = C.AV_CODEC_ID_MACE6
	AV_CODEC_ID_VMDAUDIO        CAVCodecID = C.AV_CODEC_ID_VMDAUDIO
	AV_CODEC_ID_FLAC            CAVCodecID = C.AV_CODEC_ID_FLAC
	AV_CODEC_ID_MP3ADU          CAVCodecID = C.AV_CODEC_ID_MP3ADU
	AV_CODEC_ID_MP3ON4          CAVCodecID = C.AV_CODEC_ID_MP3ON4
	AV_CODEC_ID_SHORTEN         CAVCodecID = C.AV_CODEC_ID_SHORTEN
	AV_CODEC_ID_ALAC            CAVCodecID = C.AV_CODEC_ID_ALAC
	AV_CODEC_ID_WESTWOOD_SND1   CAVCodecID = C.AV_CODEC_ID_WESTWOOD_SND1
	AV_CODEC_ID_GSM             CAVCodecID = C.AV_CODEC_ID_GSM ///< as in Berlin toast format
	AV_CODEC_ID_QDM2            CAVCodecID = C.AV_CODEC_ID_QDM2
	AV_CODEC_ID_COOK            CAVCodecID = C.AV_CODEC_ID_COOK
	AV_CODEC_ID_TRUESPEECH      CAVCodecID = C.AV_CODEC_ID_TRUESPEECH
	AV_CODEC_ID_TTA             CAVCodecID = C.AV_CODEC_ID_TTA
	AV_CODEC_ID_SMACKAUDIO      CAVCodecID = C.AV_CODEC_ID_SMACKAUDIO
	AV_CODEC_ID_QCELP           CAVCodecID = C.AV_CODEC_ID_QCELP
	AV_CODEC_ID_WAVPACK         CAVCodecID = C.AV_CODEC_ID_WAVPACK
	AV_CODEC_ID_DSICINAUDIO     CAVCodecID = C.AV_CODEC_ID_DSICINAUDIO
	AV_CODEC_ID_IMC             CAVCodecID = C.AV_CODEC_ID_IMC
	AV_CODEC_ID_MUSEPACK7       CAVCodecID = C.AV_CODEC_ID_MUSEPACK7
	AV_CODEC_ID_MLP             CAVCodecID = C.AV_CODEC_ID_MLP
	AV_CODEC_ID_GSM_MS          CAVCodecID = C.AV_CODEC_ID_GSM_MS /* as found in WAV */
	AV_CODEC_ID_ATRAC3          CAVCodecID = C.AV_CODEC_ID_ATRAC3
	AV_CODEC_ID_APE             CAVCodecID = C.AV_CODEC_ID_APE
	AV_CODEC_ID_NELLYMOSER      CAVCodecID = C.AV_CODEC_ID_NELLYMOSER
	AV_CODEC_ID_MUSEPACK8       CAVCodecID = C.AV_CODEC_ID_MUSEPACK8
	AV_CODEC_ID_SPEEX           CAVCodecID = C.AV_CODEC_ID_SPEEX
	AV_CODEC_ID_WMAVOICE        CAVCodecID = C.AV_CODEC_ID_WMAVOICE
	AV_CODEC_ID_WMAPRO          CAVCodecID = C.AV_CODEC_ID_WMAPRO
	AV_CODEC_ID_WMALOSSLESS     CAVCodecID = C.AV_CODEC_ID_WMALOSSLESS
	AV_CODEC_ID_ATRAC3P         CAVCodecID = C.AV_CODEC_ID_ATRAC3P
	AV_CODEC_ID_EAC3            CAVCodecID = C.AV_CODEC_ID_EAC3
	AV_CODEC_ID_SIPR            CAVCodecID = C.AV_CODEC_ID_SIPR
	AV_CODEC_ID_MP1             CAVCodecID = C.AV_CODEC_ID_MP1
	AV_CODEC_ID_TWINVQ          CAVCodecID = C.AV_CODEC_ID_TWINVQ
	AV_CODEC_ID_TRUEHD          CAVCodecID = C.AV_CODEC_ID_TRUEHD
	AV_CODEC_ID_MP4ALS          CAVCodecID = C.AV_CODEC_ID_MP4ALS
	AV_CODEC_ID_ATRAC1          CAVCodecID = C.AV_CODEC_ID_ATRAC1
	AV_CODEC_ID_BINKAUDIO_RDFT  CAVCodecID = C.AV_CODEC_ID_BINKAUDIO_RDFT
	AV_CODEC_ID_BINKAUDIO_DCT   CAVCodecID = C.AV_CODEC_ID_BINKAUDIO_DCT
	AV_CODEC_ID_AAC_LATM        CAVCodecID = C.AV_CODEC_ID_AAC_LATM
	AV_CODEC_ID_QDMC            CAVCodecID = C.AV_CODEC_ID_QDMC
	AV_CODEC_ID_CELT            CAVCodecID = C.AV_CODEC_ID_CELT
	AV_CODEC_ID_G723_1          CAVCodecID = C.AV_CODEC_ID_G723_1
	AV_CODEC_ID_G729            CAVCodecID = C.AV_CODEC_ID_G729
	AV_CODEC_ID_8SVX_EXP        CAVCodecID = C.AV_CODEC_ID_8SVX_EXP
	AV_CODEC_ID_8SVX_FIB        CAVCodecID = C.AV_CODEC_ID_8SVX_FIB
	AV_CODEC_ID_BMV_AUDIO       CAVCodecID = C.AV_CODEC_ID_BMV_AUDIO
	AV_CODEC_ID_RALF            CAVCodecID = C.AV_CODEC_ID_RALF
	AV_CODEC_ID_IAC             CAVCodecID = C.AV_CODEC_ID_IAC
	AV_CODEC_ID_ILBC            CAVCodecID = C.AV_CODEC_ID_ILBC
	AV_CODEC_ID_OPUS            CAVCodecID = C.AV_CODEC_ID_OPUS
	AV_CODEC_ID_COMFORT_NOISE   CAVCodecID = C.AV_CODEC_ID_COMFORT_NOISE
	AV_CODEC_ID_TAK             CAVCodecID = C.AV_CODEC_ID_TAK
	AV_CODEC_ID_METASOUND       CAVCodecID = C.AV_CODEC_ID_METASOUND
	AV_CODEC_ID_PAF_AUDIO       CAVCodecID = C.AV_CODEC_ID_PAF_AUDIO
	AV_CODEC_ID_ON2AVC          CAVCodecID = C.AV_CODEC_ID_ON2AVC
	AV_CODEC_ID_DSS_SP          CAVCodecID = C.AV_CODEC_ID_DSS_SP
	AV_CODEC_ID_CODEC2          CAVCodecID = C.AV_CODEC_ID_CODEC2
	AV_CODEC_ID_FFWAVESYNTH     CAVCodecID = C.AV_CODEC_ID_FFWAVESYNTH
	AV_CODEC_ID_SONIC           CAVCodecID = C.AV_CODEC_ID_SONIC
	AV_CODEC_ID_SONIC_LS        CAVCodecID = C.AV_CODEC_ID_SONIC_LS
	AV_CODEC_ID_EVRC            CAVCodecID = C.AV_CODEC_ID_EVRC
	AV_CODEC_ID_SMV             CAVCodecID = C.AV_CODEC_ID_SMV
	AV_CODEC_ID_DSD_LSBF        CAVCodecID = C.AV_CODEC_ID_DSD_LSBF
	AV_CODEC_ID_DSD_MSBF        CAVCodecID = C.AV_CODEC_ID_DSD_MSBF
	AV_CODEC_ID_DSD_LSBF_PLANAR CAVCodecID = C.AV_CODEC_ID_DSD_LSBF_PLANAR
	AV_CODEC_ID_DSD_MSBF_PLANAR CAVCodecID = C.AV_CODEC_ID_DSD_MSBF_PLANAR
	AV_CODEC_ID_4GV             CAVCodecID = C.AV_CODEC_ID_4GV
	AV_CODEC_ID_INTERPLAY_ACM   CAVCodecID = C.AV_CODEC_ID_INTERPLAY_ACM
	AV_CODEC_ID_XMA1            CAVCodecID = C.AV_CODEC_ID_XMA1
	AV_CODEC_ID_XMA2            CAVCodecID = C.AV_CODEC_ID_XMA2
	AV_CODEC_ID_DST             CAVCodecID = C.AV_CODEC_ID_DST
	AV_CODEC_ID_ATRAC3AL        CAVCodecID = C.AV_CODEC_ID_ATRAC3AL
	AV_CODEC_ID_ATRAC3PAL       CAVCodecID = C.AV_CODEC_ID_ATRAC3PAL
	AV_CODEC_ID_DOLBY_E         CAVCodecID = C.AV_CODEC_ID_DOLBY_E
	AV_CODEC_ID_APTX            CAVCodecID = C.AV_CODEC_ID_APTX
	AV_CODEC_ID_APTX_HD         CAVCodecID = C.AV_CODEC_ID_APTX_HD
	AV_CODEC_ID_SBC             CAVCodecID = C.AV_CODEC_ID_SBC
	AV_CODEC_ID_ATRAC9          CAVCodecID = C.AV_CODEC_ID_ATRAC9
	AV_CODEC_ID_HCOM            CAVCodecID = C.AV_CODEC_ID_HCOM
	AV_CODEC_ID_ACELP_KELVIN    CAVCodecID = C.AV_CODEC_ID_ACELP_KELVIN
	AV_CODEC_ID_MPEGH_3D_AUDIO  CAVCodecID = C.AV_CODEC_ID_MPEGH_3D_AUDIO
	AV_CODEC_ID_SIREN           CAVCodecID = C.AV_CODEC_ID_SIREN
	AV_CODEC_ID_HCA             CAVCodecID = C.AV_CODEC_ID_HCA
	AV_CODEC_ID_FASTAUDIO       CAVCodecID = C.AV_CODEC_ID_FASTAUDIO
	AV_CODEC_ID_MSNSIREN        CAVCodecID = C.AV_CODEC_ID_MSNSIREN
	AV_CODEC_ID_DFPWM           CAVCodecID = C.AV_CODEC_ID_DFPWM
	AV_CODEC_ID_BONK            CAVCodecID = C.AV_CODEC_ID_BONK
	AV_CODEC_ID_MISC4           CAVCodecID = C.AV_CODEC_ID_MISC4
	AV_CODEC_ID_APAC            CAVCodecID = C.AV_CODEC_ID_APAC
	AV_CODEC_ID_FTR             CAVCodecID = C.AV_CODEC_ID_FTR
	AV_CODEC_ID_WAVARC          CAVCodecID = C.AV_CODEC_ID_WAVARC
	AV_CODEC_ID_RKA             CAVCodecID = C.AV_CODEC_ID_RKA
	AV_CODEC_ID_AC4             CAVCodecID = C.AV_CODEC_ID_AC4
	AV_CODEC_ID_OSQ             CAVCodecID = C.AV_CODEC_ID_OSQ

	/* subtitle codecs */
	AV_CODEC_ID_FIRST_SUBTITLE     CAVCodecID = C.AV_CODEC_ID_FIRST_SUBTITLE ///< A dummy ID pointing at the start of subtitle codecs.
	AV_CODEC_ID_DVD_SUBTITLE       CAVCodecID = C.AV_CODEC_ID_DVD_SUBTITLE
	AV_CODEC_ID_DVB_SUBTITLE       CAVCodecID = C.AV_CODEC_ID_DVB_SUBTITLE
	AV_CODEC_ID_TEXT               CAVCodecID = C.AV_CODEC_ID_TEXT ///< raw UTF-8 text
	AV_CODEC_ID_XSUB               CAVCodecID = C.AV_CODEC_ID_XSUB
	AV_CODEC_ID_SSA                CAVCodecID = C.AV_CODEC_ID_SSA
	AV_CODEC_ID_MOV_TEXT           CAVCodecID = C.AV_CODEC_ID_MOV_TEXT
	AV_CODEC_ID_HDMV_PGS_SUBTITLE  CAVCodecID = C.AV_CODEC_ID_HDMV_PGS_SUBTITLE
	AV_CODEC_ID_DVB_TELETEXT       CAVCodecID = C.AV_CODEC_ID_DVB_TELETEXT
	AV_CODEC_ID_SRT                CAVCodecID = C.AV_CODEC_ID_SRT
	AV_CODEC_ID_MICRODVD           CAVCodecID = C.AV_CODEC_ID_MICRODVD
	AV_CODEC_ID_EIA_608            CAVCodecID = C.AV_CODEC_ID_EIA_608
	AV_CODEC_ID_JACOSUB            CAVCodecID = C.AV_CODEC_ID_JACOSUB
	AV_CODEC_ID_SAMI               CAVCodecID = C.AV_CODEC_ID_SAMI
	AV_CODEC_ID_REALTEXT           CAVCodecID = C.AV_CODEC_ID_REALTEXT
	AV_CODEC_ID_STL                CAVCodecID = C.AV_CODEC_ID_STL
	AV_CODEC_ID_SUBVIEWER1         CAVCodecID = C.AV_CODEC_ID_SUBVIEWER1
	AV_CODEC_ID_SUBVIEWER          CAVCodecID = C.AV_CODEC_ID_SUBVIEWER
	AV_CODEC_ID_SUBRIP             CAVCodecID = C.AV_CODEC_ID_SUBRIP
	AV_CODEC_ID_WEBVTT             CAVCodecID = C.AV_CODEC_ID_WEBVTT
	AV_CODEC_ID_MPL2               CAVCodecID = C.AV_CODEC_ID_MPL2
	AV_CODEC_ID_VPLAYER            CAVCodecID = C.AV_CODEC_ID_VPLAYER
	AV_CODEC_ID_PJS                CAVCodecID = C.AV_CODEC_ID_PJS
	AV_CODEC_ID_ASS                CAVCodecID = C.AV_CODEC_ID_ASS
	AV_CODEC_ID_HDMV_TEXT_SUBTITLE CAVCodecID = C.AV_CODEC_ID_HDMV_TEXT_SUBTITLE
	AV_CODEC_ID_TTML               CAVCodecID = C.AV_CODEC_ID_TTML
	AV_CODEC_ID_ARIB_CAPTION       CAVCodecID = C.AV_CODEC_ID_ARIB_CAPTION

	/* other specific kind of codecs (generally used for attachments) */
	AV_CODEC_ID_FIRST_UNKNOWN CAVCodecID = C.AV_CODEC_ID_FIRST_UNKNOWN ///< A dummy ID pointing at the start of various fake codecs.
	AV_CODEC_ID_TTF           CAVCodecID = C.AV_CODEC_ID_TTF

	AV_CODEC_ID_SCTE_35    CAVCodecID = C.AV_CODEC_ID_SCTE_35 ///< Contain timestamp estimated through PCR of program stream.
	AV_CODEC_ID_EPG        CAVCodecID = 98306
	AV_CODEC_ID_BINTEXT    CAVCodecID = C.AV_CODEC_ID_BINTEXT
	AV_CODEC_ID_XBIN       CAVCodecID = C.AV_CODEC_ID_XBIN
	AV_CODEC_ID_IDF        CAVCodecID = C.AV_CODEC_ID_IDF
	AV_CODEC_ID_OTF        CAVCodecID = C.AV_CODEC_ID_OTF
	AV_CODEC_ID_SMPTE_KLV  CAVCodecID = C.AV_CODEC_ID_SMPTE_KLV
	AV_CODEC_ID_DVD_NAV    CAVCodecID = C.AV_CODEC_ID_DVD_NAV
	AV_CODEC_ID_TIMED_ID3  CAVCodecID = C.AV_CODEC_ID_TIMED_ID3
	AV_CODEC_ID_BIN_DATA   CAVCodecID = C.AV_CODEC_ID_BIN_DATA
	AV_CODEC_ID_SMPTE_2038 CAVCodecID = C.AV_CODEC_ID_SMPTE_2038

	AV_CODEC_ID_PROBE CAVCodecID = C.AV_CODEC_ID_PROBE ///< codec_id is not known (like AV_CODEC_ID_NONE) but lavf should attempt to identify it

	AV_CODEC_ID_MPEG2TS CAVCodecID = C.AV_CODEC_ID_MPEG2TS /**< _FAKE_ codec to indicate a raw MPEG-2 TS
	 * stream (only used by libavformat) */
	AV_CODEC_ID_MPEG4SYSTEMS CAVCodecID = C.AV_CODEC_ID_MPEG4SYSTEMS /**< _FAKE_ codec to indicate a MPEG-4 Systems
	 * stream (only used by libavformat) */
	AV_CODEC_ID_FFMETADATA      CAVCodecID = C.AV_CODEC_ID_FFMETADATA      ///< Dummy codec for streams containing only metadata information.
	AV_CODEC_ID_WRAPPED_AVFRAME CAVCodecID = C.AV_CODEC_ID_WRAPPED_AVFRAME ///< Passthrough codec AVFrames wrapped in AVPacket
	/**
	 * Dummy null video codec, useful mainly for development and debugging.
	 * Null encoder/decoder discard all input and never return any output.
	 */
	AV_CODEC_ID_VNULL CAVCodecID = C.AV_CODEC_ID_VNULL
	/**
	 * Dummy null audio codec, useful mainly for development and debugging.
	 * Null encoder/decoder discard all input and never return any output.
	 */
	AV_CODEC_ID_ANULL CAVCodecID = C.AV_CODEC_ID_ANULL
)

// /**
//  * Get the type of the given codec.
//  */
// func AvcodecGetType(codec_id AVCodecID) AVMediaType {
// 	C.avcodec_get_type(C.enum_AVCodecID(codec_id))
// }

/**
 * Get the name of a codec.
 * @return  a static string identifying the codec; never NULL
 */
func AvcodecGetName(id CAVCodecID) string {
	return C.GoString(C.avcodec_get_name(C.enum_AVCodecID(id)))
}

/**
 * Return codec bits per sample.
 *
 * @param[in] codec_id the codec
 * @return Number of bits per sample or zero if unknown for the given codec.
 */
func AvGetBitsPerSample(codec_id CAVCodecID) int {
	return int(C.av_get_bits_per_sample(C.enum_AVCodecID(codec_id)))
}

/**
 * Return codec bits per sample.
 * Only return non-zero if the bits per sample is exactly correct, not an
 * approximation.
 *
 * @param[in] codec_id the codec
 * @return Number of bits per sample or zero if unknown for the given codec.
 */
func AvGetExactBitsPerSample(codec_id CAVCodecID) int {
	return int(C.av_get_exact_bits_per_sample(C.enum_AVCodecID(codec_id)))
}

/**
 * Return a name for the specified profile, if available.
 *
 * @param codec_id the ID of the codec to which the requested profile belongs
 * @param profile the profile value for which a name is requested
 * @return A name for the profile if found, NULL otherwise.
 *
 * @note unlike av_get_profile_name(), which searches a list of profiles
 *       supported by a specific decoder or encoder implementation, this
 *       function searches the list of profiles from the AVCodecDescriptor
 */
func AvcodecProfileName(codec_id CAVCodecID, profile int) string {
	return C.GoString(C.avcodec_profile_name(C.enum_AVCodecID(codec_id), C.int(profile)))
}

/**
 * Return the PCM codec associated with a sample format.
 * @param be  endianness, 0 for little, 1 for big,
 *            -1 (or anything else) for native
 * @return  AV_CODEC_ID_PCM_* or AV_CODEC_ID_NONE
 */
func av_get_pcm_codec(fmt avutil.CAVSampleFormat, be int) CAVCodecID {
	return CAVCodecID(C.av_get_pcm_codec(C.enum_AVSampleFormat(fmt), C.int(be)))
}
